changelog:
  categories:
    - title: ':sparkles: Features'
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: ':arrow_up: Dependencies'
      labels:
        - dependencies
