name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CGO_ENABLED: '0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.4'

      - name: Run go generate
        run: go generate ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Build artifacts linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -X 'github.com/spacefoot/wsproxy/internal/core.VERSION=${{ github.ref_name }}'" -o wsproxy-linux-amd64 ./cmd
      - name: Build artifacts linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="-s -X 'github.com/spacefoot/wsproxy/internal/core.VERSION=${{ github.ref_name }}'" -o wsproxy-linux-arm64 ./cmd
      - name: Build artifacts windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-s -X 'github.com/spacefoot/wsproxy/internal/core.VERSION=${{ github.ref_name }}'" -o wsproxy-windows-amd64.exe ./cmd
      - name: Build artifacts windows/arm64
        run: GOOS=windows GOARCH=arm64 go build -trimpath -ldflags="-s -X 'github.com/spacefoot/wsproxy/internal/core.VERSION=${{ github.ref_name }}'" -o wsproxy-windows-arm64.exe ./cmd

      - name: Release and publish artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wsproxy-*-*"
          generateReleaseNotes: "true"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup ko
        uses: ko-build/setup-ko@v0.6

      - name: Build and push container
        run: ko build --bare --image-label="org.opencontainers.image.source=https://github.com/${{ github.repository }}" --platform=linux/amd64,linux/arm64 --tags="latest,${{ github.ref_name }}" ./cmd
        env:
          GOFLAGS: "\"-ldflags=-s -X 'github.com/spacefoot/wsproxy/internal/core.VERSION=${{ github.ref_name }}' -X 'github.com/spacefoot/wsproxy/internal/core.DefaultAddr=:23193'\""
